export const NEW_ACTIVITY_SUCCESS = "NEW_ACTIVITY_SUCCESS";
export const DELETE_ACTIVITY = "DELETE_ACTIVITY";
export const UPDATE_ACTIVITY = "UPDATE_ACTIVITY";
export const SET_ACTIVITY = "SET_ACTIVITY";
