export const NEW_ACTIVITY_SUCCESS = "NEW_ACTIVITY_SUCCESS";
export const DELETE_ACTIVITY_SUCCESS = "DELETE_ACTIVITY";
export const UPDATE_ACTIVITY_SUCCESS = "UPDATE_ACTIVITY";
export const SET_ACTIVITY = "SET_ACTIVITY";
